Watching for file changes with StatReloader
Watching for file changes with StatReloader
[02/Mar/2020 14:36:27] "GET /api/admin/products/ HTTP/1.1" 200 8006
[02/Mar/2020 14:36:35] "GET /api/admin/products/ HTTP/1.1" 200 8006
[02/Mar/2020 14:36:37] "GET /api/admin/products/ HTTP/1.1" 200 8006
[02/Mar/2020 14:42:20] "POST /authenticate/ HTTP/1.1" 200 116
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[02/Mar/2020 17:06:27] "GET / HTTP/1.0" 400 63409
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[02/Mar/2020 20:23:06] "GET / HTTP/1.1" 400 63412
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.
Bad Request: /www.baidu.com:443
[03/Mar/2020 01:52:17] "CONNECT www.baidu.com:443 HTTP/1.0" 400 64109
Invalid HTTP_HOST header: '123.125.114.144'. You may need to add '123.125.114.144' to ALLOWED_HOSTS.
Bad Request: /http:/123.125.114.144/
[03/Mar/2020 01:56:24] "HEAD http://123.125.114.144/ HTTP/1.1" 400 65027
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /w00tw00t.at.ISC.SANS.DFind:)
[03/Mar/2020 02:25:30] "GET /w00tw00t.at.ISC.SANS.DFind:) HTTP/1.1" 400 63720
----------------------------------------
Exception happened during processing of request from ('193.202.44.194', 51914)
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Bad Request: /robots.txt
[03/Mar/2020 07:48:32] "HEAD /robots.txt HTTP/1.0" 400 63529
----------------------------------------
Exception happened during processing of request from ('54.38.92.35', 60000)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[03/Mar/2020 08:43:53] "POST /authenticate/ HTTP/1.1" 200 116
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[03/Mar/2020 08:44:19] "GET / HTTP/1.1" 400 63413
----------------------------------------
Exception happened during processing of request from ('85.185.2.80', 27481)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[03/Mar/2020 09:30:31] "GET / HTTP/1.1" 400 63412
----------------------------------------
Exception happened during processing of request from ('54.38.92.35', 60000)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
Bad Request: /
Bad Request: /
[03/Mar/2020 11:40:52] "GET / HTTP/1.1" 400 63412
[03/Mar/2020 11:40:52] "GET / HTTP/1.1" 400 63412
[03/Mar/2020 11:40:52] "GET / HTTP/1.1" 400 63412
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[03/Mar/2020 11:40:53] "GET / HTTP/1.1" 400 63412
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[03/Mar/2020 11:40:54] "GET / HTTP/1.1" 400 63412
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[03/Mar/2020 11:41:04] "GET / HTTP/1.1" 400 63412
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[03/Mar/2020 11:41:29] "GET / HTTP/1.1" 400 63412
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[03/Mar/2020 11:41:32] "GET / HTTP/1.1" 400 63412
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[03/Mar/2020 11:41:33] "GET / HTTP/1.1" 400 63412
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[03/Mar/2020 23:50:01] "GET / HTTP/1.1" 400 63410
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[04/Mar/2020 02:00:37] "GET / HTTP/1.1" 400 63409
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[04/Mar/2020 09:11:09] "GET / HTTP/1.1" 400 63412
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[04/Mar/2020 17:00:24] "GET / HTTP/1.1" 400 63413
----------------------------------------
Exception happened during processing of request from ('45.152.6.58', 64245)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /robots.txt
[04/Mar/2020 17:43:00] "HEAD /robots.txt HTTP/1.0" 400 63526
[04/Mar/2020 20:42:01] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03¦ãÊC\x83\x84Î\x9aüÅ\x14`\r\'VgØùIÿ\x1a\xa0\x16\x8aî\x0bynÅ\x8bRÞ PÛÄñ\x85é\t \x17m\x1c\x13³Ô\x0e5\x14LÐ+"ò\x19\x02ì\x80¹¥¦øÇÓ\x00"\x8a\x8a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[04/Mar/2020 20:42:01] You're accessing the development server over HTTPS, but it only supports HTTP.

[04/Mar/2020 20:42:09] code 400, message Bad HTTP/0.9 request type ("\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03Ë\x0fP\x15\x95\x91]\x07ùa&¿\x8eì\x8e\x8a£a²ëU¸¿ç'@\x13ÒÃ\x91É\x15")
[04/Mar/2020 20:42:09] You're accessing the development server over HTTPS, but it only supports HTTP.

Invalid HTTP_HOST header: 'ip.ws.126.net:443'. You may need to add 'ip.ws.126.net' to ALLOWED_HOSTS.
Bad Request: /ip.ws.126.net:443
[04/Mar/2020 20:43:26] "CONNECT ip.ws.126.net:443 HTTP/1.1" 400 63832
[04/Mar/2020 21:18:00] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03uÖq\x9d¸3±S\x9f\x1e\x17B\x9f6Ä6cC\x14ßW°\x0f£Ö?8Û÷\x99\x1cÊ \x1c>\x91¡ñB÷Ó*y\x8f\x06HUO\x97ÿSCöê\x98áe\xa0¨\x1fÞÀ¹ªY\x00"úú\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[04/Mar/2020 21:18:00] You're accessing the development server over HTTPS, but it only supports HTTP.

Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[04/Mar/2020 22:57:25] "GET / HTTP/1.1" 400 63413
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[05/Mar/2020 02:19:08] "GET / HTTP/1.1" 400 63413
[05/Mar/2020 06:39:19] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[05/Mar/2020 06:39:19] "  /*à     Cookie: mstshash=Administr" 400 -
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[05/Mar/2020 06:47:31] "GET / HTTP/1.1" 400 63411
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[05/Mar/2020 08:02:37] "GET / HTTP/1.1" 400 63413
[05/Mar/2020 08:30:01] "GET /api/categories/ HTTP/1.1" 200 1365
[05/Mar/2020 08:39:52] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03u®gj©¶\x03\x19\x8dñ\x1aÙ\x8bi=4ä\x18\x8dÁ\x1f}ÝjG\xad\x1eµ4\x92\x9a\x8b 0\x15ÕÖTÎ\x00O>×50P\x81\x04ùã\x9dKU\x9e!?ÿâo \x8c= \x11Ù\x00"jj\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[05/Mar/2020 08:39:52] You're accessing the development server over HTTPS, but it only supports HTTP.

[05/Mar/2020 08:40:38] "OPTIONS /authenticate/ HTTP/1.1" 200 0
[05/Mar/2020 08:40:39] "POST /authenticate/ HTTP/1.1" 200 116
[05/Mar/2020 08:40:42] "OPTIONS /api/admin/products/ HTTP/1.1" 200 0
[05/Mar/2020 08:40:46] "GET /api/admin/products/ HTTP/1.1" 200 8006
[05/Mar/2020 08:40:53] "OPTIONS /api/admin/categories/ HTTP/1.1" 200 0
[05/Mar/2020 08:40:53] "OPTIONS /api/admin/brands/ HTTP/1.1" 200 0
[05/Mar/2020 08:40:53] "OPTIONS /api/admin/products/1 HTTP/1.1" 200 0
[05/Mar/2020 08:40:54] "GET /api/admin/categories/ HTTP/1.1" 200 1365
[05/Mar/2020 08:40:54] "GET /api/admin/products/1 HTTP/1.1" 301 0
[05/Mar/2020 08:40:54] "OPTIONS /api/admin/products/1/ HTTP/1.1" 200 0
[05/Mar/2020 08:40:55] "GET /api/admin/brands/ HTTP/1.1" 200 195
[05/Mar/2020 08:40:55] "GET /api/admin/products/1/ HTTP/1.1" 200 788
[05/Mar/2020 08:40:56] "OPTIONS /api/admin/products/1/uploads/ HTTP/1.1" 200 0
[05/Mar/2020 08:40:56] "GET /api/admin/products/1/uploads/ HTTP/1.1" 200 79
[05/Mar/2020 08:40:57] "OPTIONS /api/admin/products/1/variations/ HTTP/1.1" 200 0
Not Found: /media/robot_dhxcWA7.png
[05/Mar/2020 08:40:57] "GET /media/robot_dhxcWA7.png HTTP/1.1" 404 1802
[05/Mar/2020 08:40:58] "GET /api/admin/products/1/variations/ HTTP/1.1" 200 390
[05/Mar/2020 08:40:58] "OPTIONS /api/admin/products/1/specs/ HTTP/1.1" 200 0
Not Found: /media/robot_dhxcWA7.png
[05/Mar/2020 08:40:58] "GET /media/robot_dhxcWA7.png HTTP/1.1" 404 1802
[05/Mar/2020 08:40:59] "GET /api/admin/products/1/specs/ HTTP/1.1" 200 152
Not Found: /media/robot_dhxcWA7.png
[05/Mar/2020 08:40:59] "GET /media/robot_dhxcWA7.png HTTP/1.1" 404 1802
[05/Mar/2020 08:40:59] "GET /api/admin/products/1/variations/ HTTP/1.1" 200 390
Not Found: /media/robot_dhxcWA7.png
[05/Mar/2020 08:41:01] "GET /media/robot_dhxcWA7.png HTTP/1.1" 404 1802
[05/Mar/2020 08:41:01] "GET /api/admin/products/1/specs/ HTTP/1.1" 200 152
Not Found: /media/robot_dhxcWA7.png
[05/Mar/2020 08:41:03] "GET /media/robot_dhxcWA7.png HTTP/1.1" 404 1802
Not Found: /media/robot_dhxcWA7.png
[05/Mar/2020 08:41:04] "GET /media/robot_dhxcWA7.png HTTP/1.1" 404 1802
[05/Mar/2020 08:41:10] "GET /api/categories/ HTTP/1.1" 200 1365
/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/pagination.py:198: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.Item'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[05/Mar/2020 08:41:11] "GET /api/categories/cat_two/?limit=20&page=1 HTTP/1.1" 200 52
[05/Mar/2020 08:41:20] "GET /api/categories/zz/?limit=20&page=1 HTTP/1.1" 200 52
[05/Mar/2020 08:41:21] "GET /api/categories/ HTTP/1.1" 200 1365
[05/Mar/2020 08:41:26] "GET /api/categories/1111111111111/?limit=20&page=1 HTTP/1.1" 200 52
[05/Mar/2020 08:41:26] "GET /api/categories/ HTTP/1.1" 200 1365
[05/Mar/2020 08:41:29] "GET /api/categories/ HTTP/1.1" 200 1365
Internal Server Error: /api/categories/cat_one/
Traceback (most recent call last):
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/mixins.py", line 45, in list
    return self.get_paginated_response(serializer.data)
  File "/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super(ListSerializer, self).data
  File "/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/serializers.py", line 686, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/serializers.py", line 686, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/serializers.py", line 513, in to_representation
    fields = self._readable_fields
  File "/home/behzad/store/venv/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/serializers.py", line 376, in _readable_fields
    field for field in self.fields.values()
  File "/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/serializers.py", line 363, in fields
    for key, value in self.get_fields().items():
  File "/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/serializers.py", line 1025, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/serializers.py", line 1126, in get_field_names
    serializer_class=self.__class__.__name__
AssertionError: The field 'specs' was declared on serializer ItemSerializer, but has not been included in the 'fields' option.
[05/Mar/2020 08:41:30] "GET /api/categories/cat_one/?limit=20&page=1 HTTP/1.1" 500 19542
Performing system checks...

System check identified no issues (0 silenced).
March 02, 2020 - 14:36:20
Django version 2.2.4, using settings 'home.settings.dev'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Invalid HTTP_HOST header: 'berbidvps.4.2.2.4:8000'. You may need to add 'berbidvps.4.2.2.4' to ALLOWED_HOSTS.
Bad Request: /
[05/Mar/2020 10:47:24] "GET / HTTP/1.1" 400 61787
[05/Mar/2020 13:29:38] code 400, message Bad request syntax ('\x03\x00\x00\x13\x0eà\x00\x00\x00\x00\x00\x01\x00\x08\x00\x03\x00\x00\x00')
[05/Mar/2020 13:29:38] "  à          " 400 -
                                                                                                                                                                                                                                                    Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/behzad/store/venv/lib/python3.6/site-packages/rest_framework/pagination.py:198: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'core.models.Item'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[05/Mar/2020 14:08:12] "GET /api/categories/cat_one/?limit=20&page=1 HTTP/1.1" 200 2243
[05/Mar/2020 14:08:16] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00æ\x01\x00\x00â\x03\x03Î\x98\x94ÝÛ©3ý."\x9fKn')
[05/Mar/2020 14:08:16] You're accessing the development server over HTTPS, but it only supports HTTP.

[05/Mar/2020 14:08:35] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03uÝZ&\x19uF9-ì\x8aoÎê5\x1d\x13\x8d^\r\x93&1tiQ¹è·Y¹\x90 \x94a¿\x01«t¼Ï\x94yô®£79N\x84\x9a\x83¢\x81\x8e©')
[05/Mar/2020 14:08:35] You're accessing the development server over HTTPS, but it only supports HTTP.

[05/Mar/2020 14:08:35] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x035×`\x1eàZý©ðþ\x8c\x9e\tÌT\x1dy(ð\x97\x16 |61[ýF\x01\x0c\x03ð @rã¡õ°\x8fd\x06ç,\x87\x9cd2\'EÉ\x18Y ÿ-r_ÇÄF\x0c\x10ò(\x00"ÚÚ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[05/Mar/2020 14:08:35] You're accessing the development server over HTTPS, but it only supports HTTP.

[05/Mar/2020 14:08:42] "GET /api/categories/cat_one/?limit=20&page=1 HTTP/1.1" 200 12768
[05/Mar/2020 14:08:43] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[05/Mar/2020 14:08:43] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[05/Mar/2020 14:08:43] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[05/Mar/2020 14:08:43] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[05/Mar/2020 14:08:43] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[05/Mar/2020 14:08:43] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[05/Mar/2020 14:08:43] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37608
[05/Mar/2020 14:08:43] "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
[05/Mar/2020 14:08:43] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[05/Mar/2020 14:08:43] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[05/Mar/2020 14:08:43] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[05/Mar/2020 14:08:44] "GET /favicon.ico HTTP/1.1" 404 2665
[05/Mar/2020 14:08:45] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03®K¢·%\'Ä\x05¹á\x184;é\x0bHòv\x91©§%\x01Tç\x1d²"ä\x8c\x16) \x04`à\x96\x18\x01mãUVøîÿ\x940g±£¸kéø:½\x83ø\x95\x9a3.è\x92\x00"ZZ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[05/Mar/2020 14:08:45] You're accessing the development server over HTTPS, but it only supports HTTP.

[05/Mar/2020 14:08:45] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x97\x12|\x00\x0c<¤ÝÜ9Øêù]\x87N¨Êtp ½\x87ë~\x1b±M\x98ù©ì P¦â\x0fÕ=ÎäÉ9ï\x99\x9b\x01¤(ªY¿öÊ\x87S\x10\x8b¶u\xadq\x912]\x00"ZZ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[05/Mar/2020 14:08:45] You're accessing the development server over HTTPS, but it only supports HTTP.

[05/Mar/2020 14:09:41] "GET /api/categories/cat_one/?limit=20&page=1 HTTP/1.1" 200 2243
Performing system checks...

System check identified no issues (0 silenced).
March 05, 2020 - 14:08:03
Django version 2.2.4, using settings 'home.settings.dev'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
